version: "2"

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  gocyclo:
    min-complexity: 50
  dupl:
    threshold: 150
  goconst:
    min-len: 3
    min-occurrences: 5
  misspell:
    locale: US
  lll:
    line-length: 120
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - commentedOutCode
      - hugeParam

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gocritic

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - goconst
    - path: test/
      linters:
        - gocyclo
        - dupl
        - goconst
  exclude-dirs:
    - vendor
  exclude-files:
    - ".*\\.pb\\.go$"

run:
  timeout: 5m
  tests: true
